### ISSUE TITLE
Wrong spelling in AsyncHBaseStringStore.apply

### ISSUE THREAD

**Issue by yaochitc** [twitter/storehaus#270]
Should the returned instance of the apply method be AsyncHBaseStringStore instead of AsyncHBaseLongStore?

object AsyncHBaseStringStore {
  def apply(quorumNames: Seq[String],
            table: String,
            columnFamily: String,
            column: String,
            threads: Int=4): AsyncHBaseLongStore = {
    val store = new AsyncHBaseLongStore(quorumNames, table, columnFamily, column, new HBaseClient(quorumNames.mkString(",")), threads)
    store.validateConfiguration()
    store
  }
}

**Comment by MansurAshraf** [comment]
Thanks, created a Patch with the fix
