### ISSUE TITLE
ElasticSearch test is flakey

### ISSUE THREAD

**Issue by johnynek** [twitter/storehaus#296]
`[info] ElasticSearchStoreSpecs:
[info] ElasticSearch Store
[info] - should Put a value *** FAILED ***
[info]   None did not equal Some(Person(Joe,Smith,29)) (ElasticSearchStoreSpecs.scala:52)`

**Comment by BenFradet** [comment]
I'll investigate this one this week.

**Comment by johnynek** [comment]
Thanks a ton!
